# -*- coding: utf-8 -*-
"""Копия блокнота "Dataframes.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jnym6hmlB254krNl1YFDMIUcvavIaacA

# Упражнения на работу с датафреймами

## Инструкция по выполнению задания

После выполнения задания, его нужно отправить на проверку. Для этого достаточно предоставить доступ к файлу и отправить ссылку в соответствующее поле LMS курса.

Удачи в выполнении заданий!

## Импортируе библиотеку pandas
И numpy за одно.
"""

import pandas as pd
import numpy as np

"""### Упражнение 1
Сделайте датафрейм из представленных ниже списков.
"""

raw1 = ['Иванов Иван Иванович', 41, 'Водитель']
raw2 = ['Петров Петр Петрович', 52, 'Менеджер']
raw3 = ['Сидорова Валентина Витальевна', 30, 'Специалист по недвижимости']
# заголовки таблицы
columns = ['Ф.И.О.', 'Возраст', 'Должность']

values  = [raw1, raw2 , raw3] 

table = pd.DataFrame(data = values, columns=columns)
table
print(type(raw1))

"""### Упражнение 2
С помощью метода read_csv() загрузите датафрейм из файла по [ссылке](https://people.sc.fsu.edu/~jburkardt/data/csv/oscar_age_female.csv). Файл содержит информацию о женщинах, получивших премию Оскар. Для работы с файлом можете загрузить его на дисковое пространство виртуальной машины (значок папки в левой верхней части экрана).
С помощью метода head() выведите начало таблицы на экран.
"""

oscar_age_female = pd.read_csv("/content/oscar_age_female.csv")
oscar_age_female.head(3)

"""### Упражнение 3
Оскар у некоторых актрис был присужден сразу за несколько фильмов. Из-за этого заголовки таблицы и ее содержимое при создании датафрейма немного не совпадают. Давайте добавим столбец 'Movie2', чтобы датафрейм отображался корректно.
Для того, чтобы это сделать вам может понадобиться справочная информация по методу  [read_csv()](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html).   
"""

oscar_age_female = pd.read_csv("/content/oscar_age_female.csv")
values = []
oscar_age_female.columns = ["Year", "Age", "Name", "Movie", "Movie2"]
oscar_age_female

"""### Упражнение 4 

Выведите на экран только те записи, где Оскар дали за несколько фильмов.
"""

oscar = oscar_age_female[["Movie", "Movie2"]]
oscar 

oscar[oscar.Movie2.notnull()]

"""### Упражнение 5 

Выведите на экран только те записи, где актриса старше 30 лет.
"""

oscarYear = oscar_age_female[["Age"]]
oscarYear 
oscarYear[oscarYear["Age"] > 30]