# -*- coding: utf-8 -*-
"""урок 8 1 "OpenCV1.ipynb"
Automatically generated by Colaboratory.
# Упражнения на загрузку изображений, изменение разрешения, обрезку
## Инструкция по выполнению задания
Ниже находится несколько  упражнений, представляющих собой код с пропущенными фрагментами, которые надо воспроизвести. Часть из этих упражнений очень простые, над некоторыми надо хорошенько подумать.
Чтобы выполнить это задание, нужно сохранить копию файла себе на Google Диск.
После выполнения задания, его нужно отправить на проверку. Для этого достаточно предоставить доступ к файлу и отправить ссылку в соответствующее поле LMS курса.
Удачи в выполнении заданий!

### Импортируем библиотеки для этого задания
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2 # импортируем OpenCV
from matplotlib import pyplot as plt # импортируем matplotlib
import numpy as np # импортируем numpy
from google.colab import drive
from matplotlib.image import imread

"""### Упражнение 1
Загрузите цветное изображение [мема](https://drive.google.com/file/d/1c6juvYk3orKzClcQ7rd40eV5WRsIwP4q/view?usp=sharing) и выведите его на экран средствами openCV и matplotlib. Помните, что по умолчанию библиотека openCV цветное изображение воспринимает как BGR (картинка будет выглядеть синей, скорее всего), а не RGB. Для нормального отображения нужно дополнительно преобразовать цветовую схему.
"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.image import imread
import cv2

img = cv2.imread('/content/drive/MyDrive/zhencshiny_37098706_orig_.jpeg')
img_color = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img_color)



"""### Упражнение 2
RGB изображение представляет собой массив, где на каждый пиксель приходится 3 числа. Выведите на экран (можно с помощью matplotlib) раздельно три изображения (значения красного, зеленого и синего каналов). 
"""

colorRED = img_color[10][460]
print(colorRED)
colorG = img_color[240][50]
print(colorG)
colorB = img_color[210][50]
print(colorB)

"""### Упражнение 3
Выведем на экран часть изображения, где содержится лицо персонажа мема. При этом нужно помнить, что можно задавать индексы пикселей: сперва указывается срез по оси У, а потом по оси Х.
"""

from google.colab.patches import cv2_imshow
image = cv2.imread('/content/drive/MyDrive/zhencshiny_37098706_orig_.jpeg')
img_colorfase = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

from numpy.ma.core import size
import sys
import numpy as np

cropped_image = image[70:270, 200:300]
cv2_imshow(cropped_image)

"""### Упражнение 4
Функцией resize() увеличьте размер изображения в 2 раза.
"""

big_size = cv2.resize(cropped_image, (100*2, 200 * 2))
big_size.shape
cv2_imshow(big_size)

"""### Упражнение 5
Закрасьте любую область 100х100 пикселей красным цветом.
"""

cv2.rectangle(img_color, (150, 250), (200, 200), (255, 0, 0), -1)
plt.imshow(img_color)