# -*- coding: utf-8 -*-
"""урок 10 задание 1 "Tokenization.ipynb"

Automatically generated by Colaboratory.

# Упражнения на токенизацию

## Инструкция по выполнению задания

Ниже находится несколько  упражнений, представляющих собой код с пропущенными фрагментами, которые надо воспроизвести. Часть из этих упражнений очень простые, над некоторыми надо хорошенько подумать. 

Чтобы выполнить это задание, нужно сохранить копию файла себе на Google Диск.

После выполнения задания, его нужно отправить на проверку. Для этого достаточно предоставить доступ к файлу и отправить ссылку в соответствующее поле LMS курса

Удачи в выполнении заданий!

# Выполним импорт необходимых библиотек
"""

!pip install pymorphy2

import nltk
nltk.download('punkt') # для токенизации необходимо скачать модуль
import pymorphy2 # библиотека для лемматизации

"""## Тексты для обработки

Возьмем два текста: русский и английский и попробуем провести необходимый для предобработки анализ и преобразования. Они идентичны по смыслу и взяты из уроков английского.
"""

eng_text = '''There are different kinds of animals on our planet, and all of them 
are very important for it. For example, everybody knows that the sharks are dangerous 
for people, but they are useful for cleaning seawater. There are two types of animals: 
  domestic (or pets) and wild. People keep pets in their homes. And some wild animals 
  are very dangerous. Domestic animals live next to people, whereas wild animals’ 
  “homes” are forests, jungles, oceans and so on.'''
rus_text = '''На планете много разных видов животных, и все они очень важны для нее. 
Например, все знают, что акулы опасны для людей, но они полезны для очищения морской воды. 
Есть два вида животных – домашние (или питомцы) и дикие. Люди держат питомцев в своих домах. 
А некоторые дикие животные очень опасны. Домашние животные живут рядом с людьми, тогда как 
«дома» диких животных - это леса, джунгли, океаны и так далее.'''

"""# Упражнение 1

Из библиотеки nltk используем функцию word_tokinize() для каждого из текстов.
"""

eng_words = nltk.word_tokenize(eng_text, language='english')
eng_words = list(eng_words)
rus_words = nltk.word_tokenize(rus_text, language='russian')
rus_words = list(rus_words)
print(rus_words)
print(len(rus_words))
type(eng_words)

"""# Упражнение 2

Уберем стоп-слова и пунктуацию. Используем для этого список из nltk.corpus.stopwords.words('russian') для русскоязычного текста, для текста на английском используйте nltk.corpus.stopwords.words('english'). Не забудьте также убрать пунктуацию.
"""

nltk.download('stopwords')
import sys

fillterEngWords = eng_words[:]

print(type(fillterEngWords), type(eng_text))
for eng_word in fillterEngWords:
  if eng_word in nltk.corpus.stopwords.words('english'):
    fillterEngWords.remove(eng_word)
    
print(fillterEngWords)
print(len(eng_text))
print(len(fillterEngWords))


fillterRusWords = rus_words[:]

for rus_word in fillterRusWords:
  if rus_word in nltk.word_tokenize(rus_text, language='russian'):
    fillterRusWords.remove(rus_word)

print(fillterRusWords)
print(len(rus_text))
print(len(fillterRusWords))

punct = ['-', '.', ',', ':', ';', '«', '»', ')', '(', '’', '“', '”']
cleanEngWords = fillterEngWords[:]

for clword in fillterEngWords:
  if clword in punct:
    cleanEngWords.remove(clword)
print(cleanEngWords)
print(len(fillterEngWords))
print(len(cleanEngWords))


cleanRusWords = fillterRusWords[:]
for rus_word in fillterRusWords:
  if rus_word in punct:
    cleanRusWords.remove(rus_word)
print(cleanRusWords)
print(len(fillterRusWords))
print(len(cleanRusWords))

"""# Упражнение 3

Приведем все слова к нижнему регистру.
"""

lowerEngWords = []
for word in cleanEngWords:
  lowerEngWords.append(word.lower())
print(lowerEngWords)
lowerRusWords = []
for word in cleanRusWords:
  lowerRusWords.append(word.lower())
print(cleanRusWords)

"""# Упражнение 4

Приведем лемматизацию. Для русского текста используем библиотеку [pymorphy2](https://pymorphy2.readthedocs.io/). Для английского текста используем лемматизатор из NLTK под названием [WordNetLemmatizer](https://webdevblog.ru/podhody-lemmatizacii-s-primerami-v-python/).
"""

from nltk.stem import WordNetLemmatizer 
nltk.download('wordnet')
import nltk
nltk.download('omw-1.4')

import pymorphy2
import nltk
nltk.download('wordnet')
nltk.download('pymorphy2')
from nltk.stem import WordNetLemmatizer
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()
for i in cleanEngWords:
  print(lemmatizer.lemmatize(i))

lemmatizer = WordNetLemmatizer()
for i in cleanRusWords:
  print(lemmatizer.lemmatize(i))

"""# Упражнение 5

При лемматизации русского текста с помощью pymorphy2 у вас получилось несколько вариантов результатов анализа на каждое слово. Сделайте список, где сохранятся только самые вероятные варианты (по одному на слово).
"""

words_Ru = []
for i in cleanRusWords:
  morph = pymorphy2.MorphAnalyzer()
  words_Ru.append(i)
print(words_Ru)